### ISSUE TITLE
Init documentation site

### ISSUE THREAD

**Issue by equinusocio** [wonderflow-bv/design#1]
## What

We need a site generator to build and deploy the design system documentation site.

## How

We choose to use [Next.js](https://nextjs.org/) to build the design system documentation site. We can do it by using [its CLI tool](https://nextjs.org/docs/getting-started#setup). We also need to properly configure development tools like linters, common vscode extensions, postcss etc

## To do

- [x] Prettier
- [x] Eslint
- [x] Stylelint
- [x] Commitlint/Commitizen
- [x] Postcss

**Comment by alessio-libardi** [comment]
I would also add CI + CD + Release Flow to have a complete reusable flow for the design and react-components repo.

**Comment by equinusocio** [comment]
> I would also add CI + CD + Release Flow to have a complete reusable flow for the tokens and react-components repo.

Feel free to edit and add what is missing 👍

**Comment by alessio-libardi** [comment]
Hello @equinusocio I'm configuring the workspace, for postcss is it ok if I use the [preset-env](https://github.com/csstools/postcss-preset-env) and then you tweak the postcss configuration as pleased?

Also, I would separate the initialization of the workspace from the CI + CD workflow creating another issue for it.

**Comment by equinusocio** [comment]
> Hello @equinusocio I'm configuring the workspace, for postcss is it ok if I use the preset-env and then you tweak the postcss configuration as pleased?

yes it's fine. Nextjs supports postcss out of the box by just adding the configuration file on the root.
