### ISSUE TITLE
CI + CD + Release Flow

### ISSUE THREAD

**Issue by alessio-libardi** [wonderflow-bv/design#10]
### Discussed in https://github.com/wonderflow-bv/design/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **alessio-libardi** June 25, 2021</sup>
Hello everyone, I was thinking on how to manage CI/CD and the Release flow.

Following my thoughts on a possible process to introduce:

## CI (Continous Integration) :art:
The `continous-integration.yml` will define a Github Actions automatically triggered on a pull request directed to the `main` branch.

This action will ensure the following to prevent bad code to go the `main` branch:
* Check the format of the code to maintain code quality
* Check the linting of the code to maintain code quality
* Run tests to prevent from regression bugs
* Build the code to prevent building errors to arise 

## CD (Continous Deployment) :rocket:
The `continous-deployment.yml` will define a Github Actions automatically triggered on a release creation automatically deploying the website to Github Pages.

The automatically deployed website will also keep the history of versions so that the user will be able to look at the documentation of the version it uses.

## Release :bookmark:
The `release.yml` will define a Github Actions triggerable from within the repository Actions panel to create a release for a certain release branch.

The release action will do the following:
* Automatically create a release
* Create the changelog for the release and update the project changelog
* Create the tag and automatically name the release based on the new tag created
* Bump the package version</div>

**Comment by alessio-libardi** [comment]
@equinusocio Just a question more related to the build and deploy of the design system documentation.

Do we need server-side rendering or is it ok to build and deploy a static website? Depending on this we will deploy on Github Pages or Vercel.

**Comment by equinusocio** [comment]
LGTM
