### ISSUE TITLE
Add Notifications feature to Snackbar

### ISSUE THREAD

**Issue by SRFeesha** [wonderflow-bv/design#224]
### Feature description

Make the Snackbar component ready to be used also for notifications

### Describe the solution you'd like

- [x] Update `Snackbar` component and make it dismissable
- [x] Fix the `elevated` prop (right now is documented but doesn't trigger shadow on component)
- [x] Add optional actions at the bottom of (or aside) the Snackbar (?)
- [x] Fixed width for the snackbar (?)

### Describe alternatives you've considered

Create a component for global notifications which encapsulate `Snackbar`

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

**Comment by equinusocio** [comment]
> Update Snackbar component and make it dismissable
> Add optional actions at the bottom of (or aside) the Snackbar (?)

These are the same.

> Fix the elevated prop (right now is documented but doesn't trigger shadow on component)
This prop has been removed when we introduced [`Elevator`](https://design.wonderflow.ai/develop/components/elevator/). So the doc should be updated
