### ISSUE TITLE
Search feature in the design portal

### ISSUE THREAD

**Issue by SRFeesha** [wonderflow-bv/design#26]
**Is your feature request related to a problem? Please describe.**
I'd like to add a search functionality inside the design portal. It's a feature users expect to find and it enhances the effectiveness of the documentation, especially for new users.

**Describe the solution you'd like**
I'd like to have a searchbar in a prominent position (eg: sidebar or navbar). 
Nice to have: 
- Search suggestion
- Autocomplete
- UI consistent with the site

**Additional context**
An industry standard for this kind of thing is [Algolia Search](https://www.algolia.com/products/search-and-discovery/hosted-search-api/)

**Comment by SRFeesha** [comment]
Algolia has a product designed explicitly to search things inside a documentation ✨ 

https://docsearch.algolia.com/

**Comment by equinusocio** [comment]
Good! Once we have a stable version of the website we can try to join the baracca too.
