### ISSUE TITLE
Enable font size preview on contrast calculator

### ISSUE THREAD

**Issue by alessio-libardi** [wonderflow-bv/design#51]
**Describe the bug**
In the foundation color article, within the last "Calculating contrast" section, the font-size selector isn't working.

**To Reproduce**

1. Go to the [Calculating contrast](https://design.wonderflow.ai/design/foundation/colors/#calculating-contrast) section 
2. Select a different font-size to test

**Expected behavior**
The font-size on the left should change and the contrast ratio should be calculated accordingly.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome

**Comment by equinusocio** [comment]
This is the expected behaviour. The font-size picker is working and the ration is updated correctly. The preview on the left is just meant to preview the colors, not the font-size which can be very small at 14px.

**Comment by equinusocio** [comment]
Now live https://design.wonderflow.ai/design/foundation/colors/#calculating-contrast
