### ISSUE TITLE
New recipe: notifications

### ISSUE THREAD

**Issue by equinusocio** [wonderflow-bv/design#64]
Write recipe about how to handle notifications

**Comment by SRFeesha** [comment]
## To do

**Component**
- [ ] Update Snackbar component and make it dismissable
- [ ] Fix the elevated props
- [ ] Add optional actions at the bottom of (or aside) the Snackbar (?)

**Recipe**
- [ ] Types of notifications
- [ ] Use cases
- [ ] Placement
- [ ] Behaviour (dismissable or persistent )
- [ ] Timing
